#ifndef CERISSE_RZ_FINITE_VOLUME_H_
#define CERISSE_RZ_FINITE_VOLUME_H_

#include <AMReX_Array4.H>
#include <AMReX_GpuQualifiers.H>
#include <AMReX_REAL.H>

namespace cerisse::rz_fv {

AMREX_GPU_DEVICE AMREX_FORCE_INLINE void
annular_average_radial_center_weights(
    const int target_index, const int stencil_lo,
    const amrex::Real radial_origin_over_dr,
    amrex::Real weight[3]) noexcept
{
  using amrex::Real;

  Real first_moment[3];
  Real second_moment[3];
  for (int q = 0; q < 3; ++q) {
    const Real centre =
        radial_origin_over_dr + Real(stencil_lo + q) + Real(0.5);
    first_moment[q] = centre + Real(1.0) / (Real(12.0) * centre);
    second_moment[q] = centre * centre + Real(0.25);
  }

  const Real target =
      radial_origin_over_dr + Real(target_index) + Real(0.5);
  const Real target2 = target * target;
  const Real a1 = first_moment[1] - first_moment[0];
  const Real a2 = first_moment[2] - first_moment[0];
  const Real b1 = second_moment[1] - second_moment[0];
  const Real b2 = second_moment[2] - second_moment[0];
  const Real rhs1 = target - first_moment[0];
  const Real rhs2 = target2 - second_moment[0];
  const Real determinant = a1 * b2 - a2 * b1;

  weight[1] = (rhs1 * b2 - a2 * rhs2) / determinant;
  weight[2] = (a1 * rhs2 - rhs1 * b1) / determinant;
  weight[0] = Real(1.0) - weight[1] - weight[2];
}

// Recover a radial cell-centre value from three annular cell averages.  The
// weights reproduce {1, r, r^2} exactly under the cylindrical measure r dr.
// Coordinates are scaled by dr, which keeps the 3x3 moment solve well scaled
// in the first ring next to the axis.
template <int NCONS, typename ConsArray>
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void
annular_average_to_radial_center_from_stencil(
    const int i, const int j, const int k, const int stencil_lo,
    const amrex::Real radial_origin_over_dr, const ConsArray& annular_average,
    amrex::Real point_state[NCONS]) noexcept
{
  using amrex::Real;

  const int index[3] = {stencil_lo, stencil_lo + 1, stencil_lo + 2};

  Real weight[3];
  annular_average_radial_center_weights(
      i, stencil_lo, radial_origin_over_dr, weight);

  for (int n = 0; n < NCONS; ++n) {
    point_state[n] =
        weight[0] * annular_average(index[0], j, k, n) +
        weight[1] * annular_average(index[1], j, k, n) +
        weight[2] * annular_average(index[2], j, k, n);
  }
}

template <int NCONS, typename ConsArray>
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void
annular_average_to_radial_center(
    const int i, const int j, const int k, const int radial_data_lo,
    const int radial_data_hi, const amrex::Real radial_origin_over_dr,
    const ConsArray& annular_average,
    amrex::Real point_state[NCONS]) noexcept
{
  int stencil_lo = i - 1;
  if (stencil_lo < radial_data_lo) stencil_lo = radial_data_lo;
  if (stencil_lo + 2 > radial_data_hi) stencil_lo = radial_data_hi - 2;
  annular_average_to_radial_center_from_stencil<NCONS>(
      i, j, k, stencil_lo, radial_origin_over_dr, annular_average,
      point_state);
}

// Recover the centre state of one real GP from three annular conservative
// averages generated by that GP's single BI-constrained continuation.  The
// slots correspond to radial cells {i-1, i, i+1}; no additional GP state or
// face-dependent boundary state is introduced.
template <int NCONS, typename AnnularStencil>
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void
annular_stencil_to_radial_center(
    const int i, const amrex::Real radial_origin_over_dr,
    const AnnularStencil& annular_average,
    amrex::Real point_state[NCONS]) noexcept
{
  amrex::Real weight[3];
  annular_average_radial_center_weights(
      i, i - 1, radial_origin_over_dr, weight);
  for (int n = 0; n < NCONS; ++n) {
    point_state[n] = weight[0] * annular_average(0, n) +
                     weight[1] * annular_average(1, n) +
                     weight[2] * annular_average(2, n);
  }
}

template <typename Closures, typename ConsArray>
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real
annular_average_to_radial_center_pressure(
    const int i, const int j, const int k, const int radial_data_lo,
    const int radial_data_hi, const amrex::Real radial_origin_over_dr,
    const ConsArray& annular_average, const Closures* closures) noexcept
{
  amrex::Real point_state[Closures::NCONS];
  amrex::Real point_primitives[Closures::NPRIM] = {amrex::Real(0.0)};
  annular_average_to_radial_center<Closures::NCONS>(
      i, j, k, radial_data_lo, radial_data_hi, radial_origin_over_dr,
      annular_average, point_state);
  closures->cons2prims_point(point_state, point_primitives);
  return point_primitives[Closures::QPRES];
}

}  // namespace cerisse::rz_fv

#endif
