TINY_PROFILE = FALSE
DEBUG   = FALSE
DIM     = 2
COMP     = gcc
CXXSTD    = c++20
USE_MPI = FALSE
USE_CUDA = FALSE
USE_OMP = FALSE
USE_GPIBM=FALSE
AMREX_NO_PROBINIT=TRUE
AMR_SOLVER = $(abspath ../../../)
AMREX_HOME = $(abspath ../../../lib/amrex)
CEXE_headers += prob.h
include $(AMR_SOLVER)/src/Make.CNS
